version: 2
jobs:
  test:
    docker:
       - image: circleci/ruby:2.4.1-node-browsers
    steps:
      - checkout
      - run:
        name: run tests
        command:   |
          mkdir /tmp/test-results && 
          touch /tmp/test-results/results.log &&
          rake test > /tmp/test-results/results.log
      - store_test_results:
          path: /tmp/test-results
          
workflows:
  version: 2
  build_and_test:
    jobs:
      - test