version: 2
jobs:
  test:
    docker:
       - image: circleci/ruby:2.4.1-node-browsers
    steps:
      - checkout
      - run: mkdir /tmp/test-results
      - run:  touch /tmp/test-results/results.log
      - run: rake test > /tmp/test-results/results.log
      - store_test_results:
          path: /tmp/test-results
          
workflows:
  version: 2
  test:
    jobs:
      - test